#!/usr/bin/env zsh

function pr {
    # https://git-scm.com/docs/git-status#Documentation/git-status.txt---porcelainltversiongt
    if [ -z "$(git status --porcelain)" ]; then
        git checkout develop
        git branch -D "pr/$1"
        git fetch -fu origin pull/$1/head:pr/$1
        git checkout pr/$1

        # Check to see if the git checkout was successful
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        if [[ "$BRANCH" == "pr/$1" ]]; then
            git pull -f origin pull/$1/head:pr/$1
        else
            echo 'Was not able to change branch';
        fi
    else
        echo 'Git not clean. Branch not changed'
    fi
}
