#!/usr/bin/env zsh
# shellcheck disable=SC1071
#
# Function to easily grep for a matching process
# Example:
#
#   psg postgres

function psg {
  FIRST=$(echo $1 | sed -e 's/^\(.\).*/\1/')
  REST=$(echo $1 | sed -e 's/^.\(.*\)/\1/')
  ps aux | grep "[$FIRST]$REST"
}
