#!/bin/sh -e
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read -r installer; do sh -c "${installer}"; done
