#!/usr/bin/env zsh
## ----------------- Bootstrap post-installation scripts ----------------- ##
# Run by run_dotfile_scripts in bootstrap.sh
# Scripts must be executable (chmod +x)
echo "-> Running post-bootstrap. Some steps may require password entry."

### set macOS configurations
if [ "${MACOS:-0}" -gt 0 ] || [ "$(uname)" = "Darwin" ]; then
    "./${DOTFILES}/macos/set-defaults.sh"
else
    echo 'Not macOS. Skipping set-defaults.sh.'
fi

### Install Poetry
if command -v pipx &>/dev/null && ! command -v poetry &>/dev/null; then
    pipx install poetry
else
    echo 'Skipping Poetry install.'
fi

### install VSCode extensions
for i in {code,code-exploration,code-insiders,code-server,codium}; do
    if [ "${CODESPACE:-0}" -gt 0 ] || [ "$(whoami)" = "codespace" ]; then
        echo 'Error: Codespaces VSCode CLI cannot install extensions.'
    else
        "./${DOTFILES}/script/vscode-extensions.sh" "$i"
    fi
done

### set shell
if ! [[ $SHELL =~ "zsh" ]] && command -v zsh &>/dev/null; then
    echo '--> Changing shell to Zsh. Password entry required.'
    [ "${LINUX:-0}" -gt 0 ] || [ "$(uname)" = 'Linux' ] &&
        command -v zsh | sudo tee -a /etc/shells
    sudo chsh -s "$(command -v zsh)" "$USER"
else
    echo 'Shell is already set to Zsh.'
fi
