#!/bin/sh -e

run_updates() {
    # find all update files and run them iteratively
    find . -name update.sh | while read updater ; do sh -c "${updater}" ; done
}

# TODO: Script to dynamically update all packages/dependencies based on OS with one command

# Update App Store apps
sudo softwareupdate -i -a

# Update Homebrew (Cask) & packages
brew update && brew upgrade && brew cleanup
